#!/bin/bash
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    systemctl stop vespid-server.service 2>/dev/null || true
    systemctl disable vespid-server.service 2>/dev/null || true
fi

exit 0
