"""Modular async log processor.

Tails the configured log files (``/var/log/secure``, ``/var/log/messages``,
Apache logs) using ``asyncio`` and dispatches parsed lines to the
``SlidingWindowDetector``. When a rule trips, the offending IP is published
to the DataBus and pushed to the NFTables manager (``shield_local``).

On startup, if ``catchup_on_start`` is enabled the tailer resumes from the
last saved file offset (or reads from the beginning when no offset exists).
Syslog timestamps are parsed so the sliding-window detector receives
accurate wall-clock times even during the catchup phase.
"""

from __future__ import annotations

import asyncio
import logging
import os
from collections import deque
from collections.abc import Awaitable, Callable

from .config import CONFIG, STATE_DIR, BruteForceRule, LogSource, ShieldConfig
from .custom_rules import CustomRuleEngine
from .databus import BUS, DataBus
from .detectors import CorrelationDetector, Detection, SlidingWindowDetector
from .file_tailer import tail_file
from .log_offset_store import OffsetStore
from .log_parsers import ParsedLine
from .logging_setup import audit

log = logging.getLogger("vespid.logproc")

from .auditd.detector import HostDetection, HostDetector, ProcessTree  # noqa: E402
from .auditd.mode_manager import ModeManager  # noqa: E402
from .auditd.parser import AuditdAssembler  # noqa: E402
from .auditd.scorer import HostScorer  # noqa: E402

try:
    from .auditd.prerequisites import check_auditd_prerequisites
except ImportError:  # pragma: no cover

    def check_auditd_prerequisites() -> bool:
        log.warning("auditd.prerequisites module not available; skipping prerequisite check")
        return False


# ---------------------------------------------------------------------------
# LogProcessor - orchestrates the tailers and the detector
# ---------------------------------------------------------------------------


class LogProcessor:
    def __init__(
        self,
        config: ShieldConfig | None = None,
        bus: DataBus | None = None,
        on_block: Callable[[Detection], Awaitable[None]] | None = None,
        on_observed: Callable[[], None] | None = None,
    ) -> None:
        self.config = config or CONFIG
        self.bus = bus or BUS
        self._custom_engine = CustomRuleEngine(self.config.custom_rules)
        # Merge built-in brute force rules with rules generated by custom engine
        all_rules = list(self.config.brute_force_rules) + self._custom_engine.brute_force_rules
        self.detector = SlidingWindowDetector(
            all_rules,
            persist_path=str(STATE_DIR / "detector_buckets.json"),
        )
        self.correlation = CorrelationDetector(
            self.config.correlation_rules,
            persist_path=str(STATE_DIR / "detector_correlation.json"),
        )
        self._on_block = on_block
        self._on_observed = on_observed
        self._stop = asyncio.Event()
        self._tasks: list[asyncio.Task] = []
        self._offsets = OffsetStore(self.config.offsets_path)
        self._line_buffer: deque[dict] = deque(maxlen=2000)

        # --- Auditd host-based pipeline initialization ---
        self._auditd_enabled = self.config.auditd.enabled
        self._loop: asyncio.AbstractEventLoop | None = None
        if self._auditd_enabled:
            self._init_auditd_pipeline()

    def _init_auditd_pipeline(self) -> None:
        """Initialize the auditd host detection pipeline components."""
        auditd_cfg = self.config.auditd

        # Advisory prerequisite check (does not block startup)
        check_auditd_prerequisites()

        # Filter custom rules to only those targeting auditd log sources
        # Prefer server-distributed rules (saved by reload_rules) over local config
        source_rules = getattr(self, "_last_custom_rules", None) or self.config.custom_rules
        auditd_rules = []
        for r in source_rules:
            if isinstance(r, dict):
                sources = r.get("log_sources", [])
                enabled = r.get("enabled", True)
            else:
                sources = getattr(r, "log_sources", [])
                enabled = getattr(r, "enabled", True)
            if "auditd" in sources and enabled:
                auditd_rules.append(r)
        self._auditd_rule_count = len(auditd_rules)
        self._auditd_tailer_spawned = False
        log.info(
            "Auditd pipeline: mode=%s, rules=%d, log_path=%s",
            auditd_cfg.mode,
            len(auditd_rules),
            auditd_cfg.log_path,
        )

        # Instantiate components
        self._auditd_assembler = AuditdAssembler()
        self._process_tree = ProcessTree(
            ttl_seconds=auditd_cfg.process_tree_ttl_seconds,
        )
        self._host_detector = HostDetector(
            rules=auditd_rules,
            process_tree=self._process_tree,
            daemon_pid=os.getpid(),
            exclude_uids=auditd_cfg.exclude_uids,
            exclude_exe_prefixes=auditd_cfg.exclude_exe_prefixes,
        )
        self._host_scorer = HostScorer(
            half_life=float(auditd_cfg.scorer_half_life_seconds),
            threshold=float(auditd_cfg.scorer_threshold),
            cooldown=float(auditd_cfg.alert_cooldown_seconds),
        )
        self._mode_manager = ModeManager(
            config_mode=auditd_cfg.mode,
            learning_duration_hours=auditd_cfg.learning_duration_hours,
        )

    def set_auditd_mode(self, mode: str) -> str:
        """Programmatically set the auditd detection mode."""
        if not hasattr(self, "_mode_manager"):
            log.warning("Auditd pipeline not initialized; cannot set mode")
            return "unknown"
        return self._mode_manager.set_mode(mode)

    def _spawn_auditd_tailer_tasks(self, loop=None, catchup=False) -> None:
        """Spawn the auditd file tailer and flush loop tasks."""
        if loop is None:
            loop = getattr(self, "_loop", None)
        if loop is None:
            log.warning("No event loop available to spawn auditd tailer")
            return

        auditd_log_path = self.config.auditd.log_path
        auditd_source = LogSource(path=auditd_log_path, parser="auditd")
        loop.create_task(
            tail_file(
                auditd_source,
                self._on_auditd_parsed_line,
                self._stop,
                offsets=self._offsets,
                catchup=catchup,
            )
        )
        loop.create_task(self._auditd_flush_loop())
        self._auditd_tailer_spawned = True
        log.info("Auditd tailer spawned: path=%s", auditd_log_path)

    def update_auditd_config(self, new_auditd: dict) -> dict:
        """Hot-reload auditd configuration from a server-pushed profile."""
        from .config import AuditdConfig

        old = self.config.auditd
        try:
            new_cfg = AuditdConfig(**new_auditd)
        except TypeError as exc:
            log.warning("Invalid auditd config dict: %s", exc)
            return {"changed_keys": [], "restart_required": False}

        changes: list[str] = []
        restart_required = False

        if new_cfg.enabled != old.enabled:
            changes.append("enabled")
            if new_cfg.enabled and not self._auditd_enabled:
                self.config.auditd = new_cfg
                self._auditd_enabled = True
                self._init_auditd_pipeline()
                if self._auditd_rule_count > 0:
                    loop = getattr(self, "_loop", None)
                    if loop is not None and not loop.is_closed():
                        loop.call_soon_threadsafe(
                            lambda: self._spawn_auditd_tailer_tasks(catchup=True)
                        )
                        log.info(
                            "Auditd pipeline enabled via profile — tailer spawned with catchup"
                        )
                    else:
                        log.info(
                            "Auditd pipeline enabled via profile — tailer will start on next restart"
                        )
                else:
                    log.info(
                        "Auditd pipeline enabled via profile — deferring tailer until rules are loaded"
                    )
            elif not new_cfg.enabled and self._auditd_enabled:
                self._auditd_enabled = False
                self.config.auditd = new_cfg
                log.info("Auditd pipeline disabled via profile")

        self.config.auditd = new_cfg

        if self._auditd_enabled and hasattr(self, "_mode_manager"):
            if new_cfg.mode != old.mode:
                self._mode_manager.set_mode(new_cfg.mode)
                changes.append("mode")

            if new_cfg.learning_duration_hours != old.learning_duration_hours:
                self._mode_manager._learning_duration_hours = new_cfg.learning_duration_hours
                changes.append("learning_duration_hours")

            if hasattr(self, "_host_scorer"):
                if new_cfg.scorer_threshold != old.scorer_threshold:
                    self._host_scorer._threshold = float(new_cfg.scorer_threshold)
                    changes.append("scorer_threshold")
                if new_cfg.scorer_half_life_seconds != old.scorer_half_life_seconds:
                    self._host_scorer._half_life = float(new_cfg.scorer_half_life_seconds)
                    changes.append("scorer_half_life_seconds")
                if new_cfg.alert_cooldown_seconds != old.alert_cooldown_seconds:
                    self._host_scorer._cooldown = float(new_cfg.alert_cooldown_seconds)
                    changes.append("alert_cooldown_seconds")

            if hasattr(self, "_process_tree"):
                if new_cfg.process_tree_ttl_seconds != old.process_tree_ttl_seconds:
                    self._process_tree._ttl_seconds = new_cfg.process_tree_ttl_seconds
                    changes.append("process_tree_ttl_seconds")

            if hasattr(self, "_host_detector"):
                if set(new_cfg.exclude_uids) != set(old.exclude_uids):
                    self._host_detector._exclude_uids = set(new_cfg.exclude_uids)
                    changes.append("exclude_uids")
                if list(new_cfg.exclude_exe_prefixes) != list(old.exclude_exe_prefixes):
                    self._host_detector._exclude_exe_prefixes = tuple(new_cfg.exclude_exe_prefixes)
                    changes.append("exclude_exe_prefixes")

            if new_cfg.log_path != old.log_path:
                restart_required = True
                changes.append("log_path")

        if changes:
            log.info(
                "Auditd config hot-reloaded: %s%s",
                ", ".join(changes),
                " (restart required)" if restart_required else "",
            )

        return {"changed_keys": changes, "restart_required": restart_required}

    async def _auditd_flush_loop(self) -> None:
        """Periodically flush stale auditd assembler buffers."""
        while not self._stop.is_set():
            try:
                await asyncio.sleep(3)
                if self._stop.is_set():
                    break
                stale_events = self._auditd_assembler.flush_stale()
                for event in stale_events:
                    detections = self._host_detector.evaluate(event)
                    if detections:
                        self._process_host_detections(detections)
            except asyncio.CancelledError:
                break
            except Exception as exc:
                log.warning("Auditd flush loop error: %s", exc)

    async def _process_auditd_line(self, line: str) -> None:
        """Process a single auditd log line through the host detection pipeline."""
        event = self._auditd_assembler.feed(line)
        if event is None:
            return
        detections = self._host_detector.evaluate(event)
        if not detections:
            return
        self._process_host_detections(detections)

    def _process_host_detections(self, detections: list[HostDetection]) -> None:
        """Route host detections through the mode gate."""
        mode = self._mode_manager.check_promotion()

        for det in detections:
            self._publish_host_threat(det)

            if mode in ("detecting", "alerting"):
                alert_needed = self._host_scorer.record_detection(det)
                if alert_needed and mode == "alerting":
                    self._dispatch_host_alert(det)

    def _publish_host_threat(self, det: HostDetection) -> None:
        """Publish a host detection to DataBus with event_kind=host_threat."""
        self.bus.publish(
            source_ip="",
            event_type="host_threat",
            action_taken="HOST_DETECTED",
            metadata={
                "event_kind": "host_threat",
                "rule_name": det.rule_name,
                "severity_weight": det.severity_weight,
                "hostname": det.hostname,
                "pid": det.pid,
                "ppid": det.ppid,
                "exe": det.exe,
                "command_line": det.command_line,
                "uid": det.uid,
                "auid": det.auid,
                "timestamp": det.timestamp,
                "parent_exe": det.parent_exe,
                "parent_command_line": det.parent_command_line,
                "raw_line": f"exe={det.exe} cmdline={det.command_line}",
            },
        )

    def _dispatch_host_alert(self, det: HostDetection) -> None:
        """Dispatch a host threat alert (alerting mode only)."""
        log.warning(
            "HOST_ALERT rule=%s host=%s exe=%s pid=%d score_threshold_crossed=True",
            det.rule_name,
            det.hostname,
            det.exe,
            det.pid,
        )
        self.bus.publish(
            source_ip="",
            event_type="host_alert",
            action_taken="ALERTED",
            metadata={
                "event_kind": "host_threat",
                "rule_name": det.rule_name,
                "severity_weight": det.severity_weight,
                "hostname": det.hostname,
                "pid": det.pid,
                "exe": det.exe,
                "command_line": det.command_line,
                "uid": det.uid,
            },
        )

    async def _on_auditd_parsed_line(self, parsed: ParsedLine) -> None:
        """Callback for auditd tail_file."""
        try:
            await self._process_auditd_line(parsed.raw)
        except Exception:
            log.exception("Auditd pipeline error for line: %s", parsed.raw[:200])

    async def _on_line(self, parsed: ParsedLine) -> None:
        # Skip excluded HTTP request paths
        if self.config.excluded_http_paths and parsed.parser.startswith(("apache", "haproxy")):
            lower = parsed.raw.lower()
            matched = next(
                (p for p in self.config.excluded_http_paths if p.lower() in lower),
                None,
            )
            if matched is not None:
                return

        if self._on_observed:
            self._on_observed()

        # Collect all ParsedLines: original + custom rule hits
        all_parsed = [parsed]
        custom_hits = self._custom_engine.evaluate(
            parsed.raw,
            source_parser=parsed.parser,
        )
        all_parsed.extend(custom_hits)

        # Append to surrounding-log ring buffer
        if self._line_buffer:
            last = self._line_buffer[-1]
            if (
                last.get("parser") == parsed.parser
                and last.get("raw") == parsed.raw
                and last.get("source_ip") == parsed.source_ip
            ):
                last["repeat"] = last.get("repeat", 1) + 1
                last["last_ts"] = parsed.timestamp
            else:
                self._line_buffer.append(
                    {
                        "raw": parsed.raw,
                        "parser": parsed.parser,
                        "source_ip": parsed.source_ip,
                        "timestamp": parsed.timestamp,
                    }
                )
        else:
            self._line_buffer.append(
                {
                    "raw": parsed.raw,
                    "parser": parsed.parser,
                    "source_ip": parsed.source_ip,
                    "timestamp": parsed.timestamp,
                }
            )

        # Feed each parsed match into the sliding-window detector
        blocked_this_line: set[str] = set()
        for p in all_parsed:
            for det in self.detector.record(
                parser=p.parser,
                source_ip=p.source_ip,
                timestamp=p.timestamp,
                raw_line=p.raw,
            ):
                if det.source_ip in blocked_this_line:
                    continue
                blocked_this_line.add(det.source_ip)

                log.warning(
                    "DETECT %s ip=%s attempts=%d window=%ds (rule=%s)",
                    det.rule.event_type,
                    det.source_ip,
                    det.attempts,
                    det.rule.window_seconds,
                    det.rule.name,
                )
                audit(
                    "detect",
                    rule=det.rule.name,
                    event_type=det.rule.event_type,
                    ip=det.source_ip,
                    attempts=det.attempts,
                    window_seconds=det.rule.window_seconds,
                )
                self.bus.publish(
                    source_ip=det.source_ip,
                    event_type=det.rule.event_type,
                    action_taken="DETECTED",
                    metadata={
                        "rule": det.rule.name,
                        "attempts": det.attempts,
                        "window_seconds": det.rule.window_seconds,
                    },
                )
                if self._on_block:
                    try:
                        await self._on_block(det)
                    except Exception as exc:  # pragma: no cover
                        log.exception("on_block handler failed: %s", exc)

        # Feed into correlation detector ONCE per log line
        for corr in self.correlation.record(
            parser=parsed.parser,
            source_ip=parsed.source_ip,
            timestamp=parsed.timestamp,
        ):
            log.warning(
                "CORRELATE %s ip=%s categories=%s window=%ds (rule=%s)",
                corr.rule.event_type,
                corr.source_ip,
                corr.categories_seen,
                corr.rule.window_seconds,
                corr.rule.name,
            )
            audit(
                "correlate",
                rule=corr.rule.name,
                event_type=corr.rule.event_type,
                ip=corr.source_ip,
                categories=corr.categories_seen,
                window_seconds=corr.rule.window_seconds,
            )
            self.bus.publish(
                source_ip=corr.source_ip,
                event_type=corr.rule.event_type,
                action_taken="DETECTED",
                metadata={
                    "rule": corr.rule.name,
                    "categories": corr.categories_seen,
                    "window_seconds": corr.rule.window_seconds,
                },
            )
            if self._on_block:
                synthetic_det = Detection(
                    rule=BruteForceRule(
                        name=corr.rule.name,
                        event_type=corr.rule.event_type,
                        max_attempts=corr.rule.min_categories,
                        window_seconds=corr.rule.window_seconds,
                        parser="correlation",
                    ),
                    source_ip=corr.source_ip,
                    attempts=len(corr.categories_seen),
                    first_seen=corr.first_seen,
                    last_seen=corr.last_seen,
                    context_lines=[
                        entry
                        for entry in self._line_buffer
                        if entry.get("source_ip") == corr.source_ip
                    ],
                )
                try:
                    await self._on_block(synthetic_det)
                except Exception as exc:  # pragma: no cover
                    log.exception("on_block handler failed (correlation): %s", exc)

    async def run(self) -> None:
        log.info("LogProcessor starting: sources=%d", len(self.config.log_sources))
        self._stop.clear()
        catchup = self.config.catchup_on_start
        loop = asyncio.get_running_loop()
        self._loop = loop

        for src in self.config.log_sources:
            self._tasks.append(
                loop.create_task(
                    tail_file(
                        src,
                        self._on_line,
                        self._stop,
                        offsets=self._offsets,
                        catchup=catchup,
                    )
                )
            )

        # Spawn auditd tailer when enabled and rules are loaded
        if self._auditd_enabled:
            if getattr(self, "_auditd_rule_count", 0) > 0:
                self._spawn_auditd_tailer_tasks(loop, catchup)
            else:
                log.info("Auditd enabled but no rules loaded — deferring tailer until rules arrive")

        # Periodic offset flush to disk (every 60s) so a crash
        # loses at most 60 seconds of file position progress.
        async def _offset_flush_loop():
            while not self._stop.is_set():
                try:
                    await asyncio.wait_for(self._stop.wait(), timeout=60)
                    break
                except asyncio.TimeoutError:
                    self._offsets.flush()

        self._tasks.append(loop.create_task(_offset_flush_loop()))

        if not self._tasks:
            log.warning("No log sources configured")
            return
        try:
            results = await asyncio.gather(*self._tasks, return_exceptions=True)
            for i, result in enumerate(results):
                if isinstance(result, Exception):
                    src_label = (
                        self.config.log_sources[i].path
                        if i < len(self.config.log_sources)
                        else f"task-{i}"
                    )
                    log.error("Tailer for %s crashed: %s", src_label, result)
        finally:
            self._offsets.flush()
            self._tasks.clear()

    def stop(self) -> None:
        self._stop.set()
        self._offsets.flush()

    def reload_rules(
        self,
        brute_force_rules: list,
        custom_rules: list,
        correlation_rules: list | None = None,
    ) -> None:
        """Hot-reload the detector with new rules without dropping events."""
        from .detectors import CorrelationDetector, SlidingWindowDetector

        try:
            new_engine = CustomRuleEngine(custom_rules)
        except Exception as exc:
            log.error("Hot-reload rejected: CustomRuleEngine failed: %s", exc)
            return

        all_rules = list(brute_force_rules) + new_engine.brute_force_rules
        new_detector = SlidingWindowDetector(
            all_rules,
            persist_path=str(STATE_DIR / "detector_buckets.json"),
        )
        new_correlation = CorrelationDetector(
            correlation_rules if correlation_rules is not None else self.config.correlation_rules,
            persist_path=str(STATE_DIR / "detector_correlation.json"),
        )

        old_names = {r.name for r in self.detector.rules}
        new_names = {r.name for r in new_detector.rules}
        added = new_names - old_names
        removed = old_names - new_names

        # Atomic swap
        self._custom_engine = new_engine
        self._last_custom_rules = custom_rules
        self.detector = new_detector
        self.correlation = new_correlation

        # Refresh the auditd HostDetector if the pipeline is active
        if self._auditd_enabled:
            auditd_rules = []
            for r in custom_rules:
                if isinstance(r, dict):
                    sources = r.get("log_sources", [])
                    enabled = r.get("enabled", True)
                else:
                    sources = getattr(r, "log_sources", [])
                    enabled = getattr(r, "enabled", True)
                if "auditd" in sources and enabled:
                    auditd_rules.append(r)
            from .auditd.detector import HostDetector

            self._host_detector = HostDetector(
                rules=auditd_rules,
                process_tree=self._process_tree,
                daemon_pid=os.getpid(),
                exclude_uids=self.config.auditd.exclude_uids,
                exclude_exe_prefixes=self.config.auditd.exclude_exe_prefixes,
            )
            self._auditd_rule_count = len(auditd_rules)
            if len(auditd_rules) > 0 and not getattr(self, "_auditd_tailer_spawned", False):
                loop = getattr(self, "_loop", None)
                if loop is not None and not loop.is_closed():
                    self._spawn_auditd_tailer_tasks(loop, catchup=True)
                    log.info("Auditd tailer spawned after rules loaded (catchup=True)")
            log.info("Auditd HostDetector refreshed: %d rules loaded", len(auditd_rules))

        log.info(
            "Hot-reload complete: %d active rules (added=%s, removed=%s)",
            len(new_detector.rules),
            sorted(added) if added else "none",
            sorted(removed) if removed else "none",
        )
